sudo: required

language: generic

services:
   - docker

before_install:
   - echo "start Creating an image with dockerfile"
   - docker build -t 2hwayoung/react-app -f Dockerfile.dev .

script:
   - docker run -e CI=true 2hwayoung/react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-355670014736"
  bucket_path: "react-app"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY